// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// See github.com/flynn/flynn/logaggregator/types StreamType
type LogAggregatorStreamType int32

const (
	LogAggregatorStreamType_STDOUT  LogAggregatorStreamType = 0
	LogAggregatorStreamType_STDERR  LogAggregatorStreamType = 1
	LogAggregatorStreamType_INIT    LogAggregatorStreamType = 2
	LogAggregatorStreamType_UNKNOWN LogAggregatorStreamType = 3
)

var LogAggregatorStreamType_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
	2: "INIT",
	3: "UNKNOWN",
}

var LogAggregatorStreamType_value = map[string]int32{
	"STDOUT":  0,
	"STDERR":  1,
	"INIT":    2,
	"UNKNOWN": 3,
}

func (x LogAggregatorStreamType) String() string {
	return proto.EnumName(LogAggregatorStreamType_name, int32(x))
}

func (LogAggregatorStreamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

// See github.com/flynn/flynn/logaggregator NewMessageFromSyslog
type LogAggregatorStreamSource int32

const (
	LogAggregatorStreamSource_APP LogAggregatorStreamSource = 0
)

var LogAggregatorStreamSource_name = map[int32]string{
	0: "APP",
}

var LogAggregatorStreamSource_value = map[string]int32{
	"APP": 0,
}

func (x LogAggregatorStreamSource) String() string {
	return proto.EnumName(LogAggregatorStreamSource_name, int32(x))
}

func (LogAggregatorStreamSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

type Deployment_Status int32

const (
	Deployment_PENDING  Deployment_Status = 0
	Deployment_FAILED   Deployment_Status = 1
	Deployment_RUNNING  Deployment_Status = 2
	Deployment_COMPLETE Deployment_Status = 3
)

var Deployment_Status_name = map[int32]string{
	0: "PENDING",
	1: "FAILED",
	2: "RUNNING",
	3: "COMPLETE",
}

var Deployment_Status_value = map[string]int32{
	"PENDING":  0,
	"FAILED":   1,
	"RUNNING":  2,
	"COMPLETE": 3,
}

func (x Deployment_Status) String() string {
	return proto.EnumName(Deployment_Status_name, int32(x))
}

func (Deployment_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{10, 0}
}

type ListAppsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsRequest) Reset()         { *m = ListAppsRequest{} }
func (m *ListAppsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppsRequest) ProtoMessage()    {}
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}
func (m *ListAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsRequest.Unmarshal(m, b)
}
func (m *ListAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsRequest.Marshal(b, m, deterministic)
}
func (dst *ListAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsRequest.Merge(dst, src)
}
func (m *ListAppsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppsRequest.Size(m)
}
func (m *ListAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsRequest proto.InternalMessageInfo

func (m *ListAppsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAppsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListAppsResponse struct {
	Apps                 []*App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsResponse) Reset()         { *m = ListAppsResponse{} }
func (m *ListAppsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAppsResponse) ProtoMessage()    {}
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}
func (m *ListAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsResponse.Unmarshal(m, b)
}
func (m *ListAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsResponse.Marshal(b, m, deterministic)
}
func (dst *ListAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsResponse.Merge(dst, src)
}
func (m *ListAppsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAppsResponse.Size(m)
}
func (m *ListAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsResponse proto.InternalMessageInfo

func (m *ListAppsResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *ListAppsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetAppRequest struct {
	// name = "apps/APP_ID"
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppRequest) Reset()         { *m = GetAppRequest{} }
func (m *GetAppRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppRequest) ProtoMessage()    {}
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}
func (m *GetAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppRequest.Unmarshal(m, b)
}
func (m *GetAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppRequest.Marshal(b, m, deterministic)
}
func (dst *GetAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppRequest.Merge(dst, src)
}
func (m *GetAppRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppRequest.Size(m)
}
func (m *GetAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppRequest proto.InternalMessageInfo

func (m *GetAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetReleaseRequest struct {
	// name = "apps/APP_ID/releases/RELEASE_ID"
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReleaseRequest) Reset()         { *m = GetReleaseRequest{} }
func (m *GetReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetReleaseRequest) ProtoMessage()    {}
func (*GetReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}
func (m *GetReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReleaseRequest.Unmarshal(m, b)
}
func (m *GetReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReleaseRequest.Marshal(b, m, deterministic)
}
func (dst *GetReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReleaseRequest.Merge(dst, src)
}
func (m *GetReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetReleaseRequest.Size(m)
}
func (m *GetReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReleaseRequest proto.InternalMessageInfo

func (m *GetReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamAppLogRequest struct {
	// name = "apps/APP_ID"
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Opts                 *LogAggregatorLogOpts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StreamAppLogRequest) Reset()         { *m = StreamAppLogRequest{} }
func (m *StreamAppLogRequest) String() string { return proto.CompactTextString(m) }
func (*StreamAppLogRequest) ProtoMessage()    {}
func (*StreamAppLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{4}
}
func (m *StreamAppLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAppLogRequest.Unmarshal(m, b)
}
func (m *StreamAppLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAppLogRequest.Marshal(b, m, deterministic)
}
func (dst *StreamAppLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAppLogRequest.Merge(dst, src)
}
func (m *StreamAppLogRequest) XXX_Size() int {
	return xxx_messageInfo_StreamAppLogRequest.Size(m)
}
func (m *StreamAppLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAppLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAppLogRequest proto.InternalMessageInfo

func (m *StreamAppLogRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamAppLogRequest) GetOpts() *LogAggregatorLogOpts {
	if m != nil {
		return m.Opts
	}
	return nil
}

type CreateReleaseRequest struct {
	// parent = "apps/APP_ID"
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Release              *Release `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	RequestId            string   `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReleaseRequest) Reset()         { *m = CreateReleaseRequest{} }
func (m *CreateReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReleaseRequest) ProtoMessage()    {}
func (*CreateReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{5}
}
func (m *CreateReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReleaseRequest.Unmarshal(m, b)
}
func (m *CreateReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReleaseRequest.Marshal(b, m, deterministic)
}
func (dst *CreateReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReleaseRequest.Merge(dst, src)
}
func (m *CreateReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReleaseRequest.Size(m)
}
func (m *CreateReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReleaseRequest proto.InternalMessageInfo

func (m *CreateReleaseRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateReleaseRequest) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *CreateReleaseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type CreateDeploymentRequest struct {
	// parent = "apps/APP_ID"
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// release = Release.name
	Release              string   `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	RequestId            string   `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeploymentRequest) Reset()         { *m = CreateDeploymentRequest{} }
func (m *CreateDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeploymentRequest) ProtoMessage()    {}
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{6}
}
func (m *CreateDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeploymentRequest.Unmarshal(m, b)
}
func (m *CreateDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeploymentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeploymentRequest.Merge(dst, src)
}
func (m *CreateDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeploymentRequest.Size(m)
}
func (m *CreateDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeploymentRequest proto.InternalMessageInfo

func (m *CreateDeploymentRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateDeploymentRequest) GetRelease() string {
	if m != nil {
		return m.Release
	}
	return ""
}

func (m *CreateDeploymentRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type StreamEventsRequest struct {
	// parent = "apps/APP_ID"
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	ObjectTypes          []string `protobuf:"bytes,2,rep,name=object_types,json=objectTypes,proto3" json:"object_types,omitempty"`
	ObjectId             string   `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Post                 bool     `protobuf:"varint,4,opt,name=post,proto3" json:"post,omitempty"`
	Count                int32    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamEventsRequest) Reset()         { *m = StreamEventsRequest{} }
func (m *StreamEventsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamEventsRequest) ProtoMessage()    {}
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{7}
}
func (m *StreamEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamEventsRequest.Unmarshal(m, b)
}
func (m *StreamEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamEventsRequest.Marshal(b, m, deterministic)
}
func (dst *StreamEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamEventsRequest.Merge(dst, src)
}
func (m *StreamEventsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamEventsRequest.Size(m)
}
func (m *StreamEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamEventsRequest proto.InternalMessageInfo

func (m *StreamEventsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *StreamEventsRequest) GetObjectTypes() []string {
	if m != nil {
		return m.ObjectTypes
	}
	return nil
}

func (m *StreamEventsRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *StreamEventsRequest) GetPost() bool {
	if m != nil {
		return m.Post
	}
	return false
}

func (m *StreamEventsRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type App struct {
	// name = "apps/APP_ID"
	Name          string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string               `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Labels        map[string]string    `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamp.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	DeployTimeout int32                `protobuf:"varint,6,opt,name=deploy_timeout,json=deployTimeout,proto3" json:"deploy_timeout,omitempty"`
	Strategy      string               `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// release = Release.name
	Release              string   `protobuf:"bytes,8,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{8}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (dst *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(dst, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *App) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *App) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *App) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *App) GetDeployTimeout() int32 {
	if m != nil {
		return m.DeployTimeout
	}
	return 0
}

func (m *App) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *App) GetRelease() string {
	if m != nil {
		return m.Release
	}
	return ""
}

type Release struct {
	// name = "apps/APP_ID/releases/RELEASE_ID"
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artifacts            []string                `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Env                  map[string]string       `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string       `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Processes            map[string]*ProcessType `protobuf:"bytes,6,rep,name=processes,proto3" json:"processes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp    `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{9}
}
func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (dst *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(dst, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Release) GetArtifacts() []string {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func (m *Release) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Release) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Release) GetProcesses() map[string]*ProcessType {
	if m != nil {
		return m.Processes
	}
	return nil
}

func (m *Release) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type Deployment struct {
	// name = "apps/APP_ID/deployments/DEPLOYMENT_ID"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// old_release = Release.name
	OldRelease string `protobuf:"bytes,3,opt,name=old_release,json=oldRelease,proto3" json:"old_release,omitempty"`
	// new_release = Release.name
	NewRelease string            `protobuf:"bytes,4,opt,name=new_release,json=newRelease,proto3" json:"new_release,omitempty"`
	Strategy   string            `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Status     Deployment_Status `protobuf:"varint,6,opt,name=status,proto3,enum=controller.Deployment_Status" json:"status,omitempty"`
	Processes  map[string]int32  `protobuf:"bytes,7,rep,name=processes,proto3" json:"processes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// profobuf doesn't support maps within maps, so map[string]map[string]string
	// could not be reproduced
	Tags                 map[string]*DeploymentProcessTags `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DeployTimeout        int32                             `protobuf:"varint,9,opt,name=deploy_timeout,json=deployTimeout,proto3" json:"deploy_timeout,omitempty"`
	CreateTime           *timestamp.Timestamp              `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ExpireTime           *timestamp.Timestamp              `protobuf:"bytes,11,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	EndTime              *timestamp.Timestamp              `protobuf:"bytes,12,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{10}
}
func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (dst *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(dst, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Deployment) GetOldRelease() string {
	if m != nil {
		return m.OldRelease
	}
	return ""
}

func (m *Deployment) GetNewRelease() string {
	if m != nil {
		return m.NewRelease
	}
	return ""
}

func (m *Deployment) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *Deployment) GetStatus() Deployment_Status {
	if m != nil {
		return m.Status
	}
	return Deployment_PENDING
}

func (m *Deployment) GetProcesses() map[string]int32 {
	if m != nil {
		return m.Processes
	}
	return nil
}

func (m *Deployment) GetTags() map[string]*DeploymentProcessTags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Deployment) GetDeployTimeout() int32 {
	if m != nil {
		return m.DeployTimeout
	}
	return 0
}

func (m *Deployment) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Deployment) GetExpireTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireTime
	}
	return nil
}

func (m *Deployment) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type DeploymentProcessTags struct {
	Tags                 map[string]string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentProcessTags) Reset()         { *m = DeploymentProcessTags{} }
func (m *DeploymentProcessTags) String() string { return proto.CompactTextString(m) }
func (*DeploymentProcessTags) ProtoMessage()    {}
func (*DeploymentProcessTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{11}
}
func (m *DeploymentProcessTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentProcessTags.Unmarshal(m, b)
}
func (m *DeploymentProcessTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentProcessTags.Marshal(b, m, deterministic)
}
func (dst *DeploymentProcessTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentProcessTags.Merge(dst, src)
}
func (m *DeploymentProcessTags) XXX_Size() int {
	return xxx_messageInfo_DeploymentProcessTags.Size(m)
}
func (m *DeploymentProcessTags) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentProcessTags.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentProcessTags proto.InternalMessageInfo

func (m *DeploymentProcessTags) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Event struct {
	// name = "events/EVENT_ID"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// parent = Any.name
	Parent               string               `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Data                 *any.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{12}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Event) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type ProcessType struct {
	Args                 []string                     `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env                  map[string]string            `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ports                []*Port                      `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes              []*VolumeReq                 `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Omni                 bool                         `protobuf:"varint,5,opt,name=omni,proto3" json:"omni,omitempty"`
	HostNetwork          bool                         `protobuf:"varint,6,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	HostPidNamespace     bool                         `protobuf:"varint,7,opt,name=host_pid_namespace,json=hostPidNamespace,proto3" json:"host_pid_namespace,omitempty"`
	Service              string                       `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`
	Resurrect            bool                         `protobuf:"varint,9,opt,name=resurrect,proto3" json:"resurrect,omitempty"`
	Resources            map[string]*HostResourceSpec `protobuf:"bytes,10,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Mounts               []*HostMount                 `protobuf:"bytes,11,rep,name=mounts,proto3" json:"mounts,omitempty"`
	LinuxCapabilities    []string                     `protobuf:"bytes,12,rep,name=linux_capabilities,json=linuxCapabilities,proto3" json:"linux_capabilities,omitempty"`
	AllowedDevices       []*LibContainerDevice        `protobuf:"bytes,13,rep,name=allowed_devices,json=allowedDevices,proto3" json:"allowed_devices,omitempty"`
	WriteableCgroups     bool                         `protobuf:"varint,14,opt,name=writeable_cgroups,json=writeableCgroups,proto3" json:"writeable_cgroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ProcessType) Reset()         { *m = ProcessType{} }
func (m *ProcessType) String() string { return proto.CompactTextString(m) }
func (*ProcessType) ProtoMessage()    {}
func (*ProcessType) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{13}
}
func (m *ProcessType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessType.Unmarshal(m, b)
}
func (m *ProcessType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessType.Marshal(b, m, deterministic)
}
func (dst *ProcessType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessType.Merge(dst, src)
}
func (m *ProcessType) XXX_Size() int {
	return xxx_messageInfo_ProcessType.Size(m)
}
func (m *ProcessType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessType.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessType proto.InternalMessageInfo

func (m *ProcessType) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ProcessType) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ProcessType) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ProcessType) GetVolumes() []*VolumeReq {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *ProcessType) GetOmni() bool {
	if m != nil {
		return m.Omni
	}
	return false
}

func (m *ProcessType) GetHostNetwork() bool {
	if m != nil {
		return m.HostNetwork
	}
	return false
}

func (m *ProcessType) GetHostPidNamespace() bool {
	if m != nil {
		return m.HostPidNamespace
	}
	return false
}

func (m *ProcessType) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ProcessType) GetResurrect() bool {
	if m != nil {
		return m.Resurrect
	}
	return false
}

func (m *ProcessType) GetResources() map[string]*HostResourceSpec {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ProcessType) GetMounts() []*HostMount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *ProcessType) GetLinuxCapabilities() []string {
	if m != nil {
		return m.LinuxCapabilities
	}
	return nil
}

func (m *ProcessType) GetAllowedDevices() []*LibContainerDevice {
	if m != nil {
		return m.AllowedDevices
	}
	return nil
}

func (m *ProcessType) GetWriteableCgroups() bool {
	if m != nil {
		return m.WriteableCgroups
	}
	return false
}

type Port struct {
	Port                 int32        `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Proto                string       `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Service              *HostService `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{14}
}
func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (dst *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(dst, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Port) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Port) GetService() *HostService {
	if m != nil {
		return m.Service
	}
	return nil
}

type VolumeReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DeleteOnStop         bool     `protobuf:"varint,2,opt,name=delete_on_stop,json=deleteOnStop,proto3" json:"delete_on_stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeReq) Reset()         { *m = VolumeReq{} }
func (m *VolumeReq) String() string { return proto.CompactTextString(m) }
func (*VolumeReq) ProtoMessage()    {}
func (*VolumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{15}
}
func (m *VolumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeReq.Unmarshal(m, b)
}
func (m *VolumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeReq.Marshal(b, m, deterministic)
}
func (dst *VolumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeReq.Merge(dst, src)
}
func (m *VolumeReq) XXX_Size() int {
	return xxx_messageInfo_VolumeReq.Size(m)
}
func (m *VolumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeReq proto.InternalMessageInfo

func (m *VolumeReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *VolumeReq) GetDeleteOnStop() bool {
	if m != nil {
		return m.DeleteOnStop
	}
	return false
}

// See github.com/flynn/flynn/host/types Mount
type HostService struct {
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Create the service in service discovery
	Create               bool             `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	Check                *HostHealthCheck `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HostService) Reset()         { *m = HostService{} }
func (m *HostService) String() string { return proto.CompactTextString(m) }
func (*HostService) ProtoMessage()    {}
func (*HostService) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{16}
}
func (m *HostService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostService.Unmarshal(m, b)
}
func (m *HostService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostService.Marshal(b, m, deterministic)
}
func (dst *HostService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostService.Merge(dst, src)
}
func (m *HostService) XXX_Size() int {
	return xxx_messageInfo_HostService.Size(m)
}
func (m *HostService) XXX_DiscardUnknown() {
	xxx_messageInfo_HostService.DiscardUnknown(m)
}

var xxx_messageInfo_HostService proto.InternalMessageInfo

func (m *HostService) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *HostService) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

func (m *HostService) GetCheck() *HostHealthCheck {
	if m != nil {
		return m.Check
	}
	return nil
}

// See github.com/flynn/flynn/host/types Mount
type HostHealthCheck struct {
	// Type is one of tcp, http, https
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Interval is the time to wait between checks after the service has been
	// marked as up. It defaults to two seconds.
	Interval *duration.Duration `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Threshold is the number of consecutive checks of the same status before
	// a service will be marked as up or down after coming up for the first
	// time. It defaults to 2.
	Threshold int32 `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// If KillDown is true, the job will be killed if the service goes down (or
	// does not come up)
	KillDown bool `protobuf:"varint,5,opt,name=kill_down,json=killDown,proto3" json:"kill_down,omitempty"`
	// StartTimeout is the maximum duration that a service can take to come up
	// for the first time if KillDown is true. It defaults to ten seconds.
	StartTimeout *duration.Duration `protobuf:"bytes,6,opt,name=start_timeout,json=startTimeout,proto3" json:"start_timeout,omitempty"`
	// Extra optional config fields for http/https checks
	Path                 string   `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Host                 string   `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	Match                string   `protobuf:"bytes,9,opt,name=match,proto3" json:"match,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostHealthCheck) Reset()         { *m = HostHealthCheck{} }
func (m *HostHealthCheck) String() string { return proto.CompactTextString(m) }
func (*HostHealthCheck) ProtoMessage()    {}
func (*HostHealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{17}
}
func (m *HostHealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostHealthCheck.Unmarshal(m, b)
}
func (m *HostHealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostHealthCheck.Marshal(b, m, deterministic)
}
func (dst *HostHealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostHealthCheck.Merge(dst, src)
}
func (m *HostHealthCheck) XXX_Size() int {
	return xxx_messageInfo_HostHealthCheck.Size(m)
}
func (m *HostHealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HostHealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HostHealthCheck proto.InternalMessageInfo

func (m *HostHealthCheck) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HostHealthCheck) GetInterval() *duration.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *HostHealthCheck) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *HostHealthCheck) GetKillDown() bool {
	if m != nil {
		return m.KillDown
	}
	return false
}

func (m *HostHealthCheck) GetStartTimeout() *duration.Duration {
	if m != nil {
		return m.StartTimeout
	}
	return nil
}

func (m *HostHealthCheck) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HostHealthCheck) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HostHealthCheck) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *HostHealthCheck) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// See github.com/flynn/flynn/host/resource Spec
type HostResourceSpec struct {
	// Request, if set, is the amount of resource a job expects to consume,
	// so the job should only be placed on a host with at least this amount
	// of resource available, and once scheduled this amount of resource
	// should then be unavailable on the given host.
	Request int64 `protobuf:"varint,1,opt,name=request,proto3" json:"request,omitempty"`
	// Limit, if set, is an upper limit on the amount of resource a job can
	// consume, the outcome of hitting this limit being implementation
	// defined (e.g. a system error, throttling, catchable / uncatchable
	// signals etc.)
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostResourceSpec) Reset()         { *m = HostResourceSpec{} }
func (m *HostResourceSpec) String() string { return proto.CompactTextString(m) }
func (*HostResourceSpec) ProtoMessage()    {}
func (*HostResourceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{18}
}
func (m *HostResourceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostResourceSpec.Unmarshal(m, b)
}
func (m *HostResourceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostResourceSpec.Marshal(b, m, deterministic)
}
func (dst *HostResourceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostResourceSpec.Merge(dst, src)
}
func (m *HostResourceSpec) XXX_Size() int {
	return xxx_messageInfo_HostResourceSpec.Size(m)
}
func (m *HostResourceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_HostResourceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_HostResourceSpec proto.InternalMessageInfo

func (m *HostResourceSpec) GetRequest() int64 {
	if m != nil {
		return m.Request
	}
	return 0
}

func (m *HostResourceSpec) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// See github.com/flynn/flynn/host/types Mount
type HostMount struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Writable             bool     `protobuf:"varint,3,opt,name=writable,proto3" json:"writable,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Flags                int32    `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostMount) Reset()         { *m = HostMount{} }
func (m *HostMount) String() string { return proto.CompactTextString(m) }
func (*HostMount) ProtoMessage()    {}
func (*HostMount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{19}
}
func (m *HostMount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostMount.Unmarshal(m, b)
}
func (m *HostMount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostMount.Marshal(b, m, deterministic)
}
func (dst *HostMount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostMount.Merge(dst, src)
}
func (m *HostMount) XXX_Size() int {
	return xxx_messageInfo_HostMount.Size(m)
}
func (m *HostMount) XXX_DiscardUnknown() {
	xxx_messageInfo_HostMount.DiscardUnknown(m)
}

var xxx_messageInfo_HostMount proto.InternalMessageInfo

func (m *HostMount) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *HostMount) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *HostMount) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *HostMount) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *HostMount) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *HostMount) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

// See github.com/opencontainers/runc/libcontainer/configs Device
type LibContainerDevice struct {
	// Device type, block, char, etc.
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// Path to the device.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Major is the device's major number.
	Major int64 `protobuf:"varint,3,opt,name=major,proto3" json:"major,omitempty"`
	// Minor is the device's minor number.
	Minor int64 `protobuf:"varint,4,opt,name=minor,proto3" json:"minor,omitempty"`
	// Cgroup permissions format, rwm.
	Permissions string `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
	// FileMode permission bits for the device.
	FileMode uint32 `protobuf:"varint,6,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	// Uid of the device.
	Uid uint32 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	// Gid of the device.
	Gid uint32 `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	// Write the file to the allowed list
	Allow                bool     `protobuf:"varint,9,opt,name=allow,proto3" json:"allow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibContainerDevice) Reset()         { *m = LibContainerDevice{} }
func (m *LibContainerDevice) String() string { return proto.CompactTextString(m) }
func (*LibContainerDevice) ProtoMessage()    {}
func (*LibContainerDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{20}
}
func (m *LibContainerDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibContainerDevice.Unmarshal(m, b)
}
func (m *LibContainerDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibContainerDevice.Marshal(b, m, deterministic)
}
func (dst *LibContainerDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibContainerDevice.Merge(dst, src)
}
func (m *LibContainerDevice) XXX_Size() int {
	return xxx_messageInfo_LibContainerDevice.Size(m)
}
func (m *LibContainerDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_LibContainerDevice.DiscardUnknown(m)
}

var xxx_messageInfo_LibContainerDevice proto.InternalMessageInfo

func (m *LibContainerDevice) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LibContainerDevice) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *LibContainerDevice) GetMajor() int64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *LibContainerDevice) GetMinor() int64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *LibContainerDevice) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func (m *LibContainerDevice) GetFileMode() uint32 {
	if m != nil {
		return m.FileMode
	}
	return 0
}

func (m *LibContainerDevice) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LibContainerDevice) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *LibContainerDevice) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

// See github.com/flynn/flynn/logaggregator/client Message
type LogChunk struct {
	// host = "hosts/HOST_ID"
	// host is the host that the job was running on when this log message was
	// emitted.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// job_id = "apps/APP_ID/jobs/JOB_ID"
	Job string `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	// msg is the actual content of this log message.
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// process_type is the type of process that emitted this log message.
	ProcessType string `protobuf:"bytes,4,opt,name=process_type,json=processType,proto3" json:"process_type,omitempty"`
	// source is the source of this log message.
	Source LogAggregatorStreamSource `protobuf:"varint,5,opt,name=source,proto3,enum=controller.LogAggregatorStreamSource" json:"source,omitempty"`
	// stream is the I/O stream that emitted this message, such as "stdout" or
	// "stderr".
	Stream LogAggregatorStreamType `protobuf:"varint,6,opt,name=stream,proto3,enum=controller.LogAggregatorStreamType" json:"stream,omitempty"`
	// create_time is the time that this log line was emitted.
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogChunk) Reset()         { *m = LogChunk{} }
func (m *LogChunk) String() string { return proto.CompactTextString(m) }
func (*LogChunk) ProtoMessage()    {}
func (*LogChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{21}
}
func (m *LogChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogChunk.Unmarshal(m, b)
}
func (m *LogChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogChunk.Marshal(b, m, deterministic)
}
func (dst *LogChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogChunk.Merge(dst, src)
}
func (m *LogChunk) XXX_Size() int {
	return xxx_messageInfo_LogChunk.Size(m)
}
func (m *LogChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_LogChunk.DiscardUnknown(m)
}

var xxx_messageInfo_LogChunk proto.InternalMessageInfo

func (m *LogChunk) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogChunk) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *LogChunk) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogChunk) GetProcessType() string {
	if m != nil {
		return m.ProcessType
	}
	return ""
}

func (m *LogChunk) GetSource() LogAggregatorStreamSource {
	if m != nil {
		return m.Source
	}
	return LogAggregatorStreamSource_APP
}

func (m *LogChunk) GetStream() LogAggregatorStreamType {
	if m != nil {
		return m.Stream
	}
	return LogAggregatorStreamType_STDOUT
}

func (m *LogChunk) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

// See github.com/flynn/flynn/logaggregator/types LogOpts
type LogAggregatorLogOpts struct {
	Follow bool `protobuf:"varint,1,opt,name=follow,proto3" json:"follow,omitempty"`
	// job = "apps/APP_ID/jobs/JOB_ID"
	Job                  string                    `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Lines                int32                     `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
	ProcessType          string                    `protobuf:"bytes,4,opt,name=process_type,json=processType,proto3" json:"process_type,omitempty"`
	StreamTypes          []LogAggregatorStreamType `protobuf:"varint,5,rep,packed,name=stream_types,json=streamTypes,proto3,enum=controller.LogAggregatorStreamType" json:"stream_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LogAggregatorLogOpts) Reset()         { *m = LogAggregatorLogOpts{} }
func (m *LogAggregatorLogOpts) String() string { return proto.CompactTextString(m) }
func (*LogAggregatorLogOpts) ProtoMessage()    {}
func (*LogAggregatorLogOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{22}
}
func (m *LogAggregatorLogOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogAggregatorLogOpts.Unmarshal(m, b)
}
func (m *LogAggregatorLogOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogAggregatorLogOpts.Marshal(b, m, deterministic)
}
func (dst *LogAggregatorLogOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogAggregatorLogOpts.Merge(dst, src)
}
func (m *LogAggregatorLogOpts) XXX_Size() int {
	return xxx_messageInfo_LogAggregatorLogOpts.Size(m)
}
func (m *LogAggregatorLogOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_LogAggregatorLogOpts.DiscardUnknown(m)
}

var xxx_messageInfo_LogAggregatorLogOpts proto.InternalMessageInfo

func (m *LogAggregatorLogOpts) GetFollow() bool {
	if m != nil {
		return m.Follow
	}
	return false
}

func (m *LogAggregatorLogOpts) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *LogAggregatorLogOpts) GetLines() int32 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *LogAggregatorLogOpts) GetProcessType() string {
	if m != nil {
		return m.ProcessType
	}
	return ""
}

func (m *LogAggregatorLogOpts) GetStreamTypes() []LogAggregatorStreamType {
	if m != nil {
		return m.StreamTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*ListAppsRequest)(nil), "controller.ListAppsRequest")
	proto.RegisterType((*ListAppsResponse)(nil), "controller.ListAppsResponse")
	proto.RegisterType((*GetAppRequest)(nil), "controller.GetAppRequest")
	proto.RegisterType((*GetReleaseRequest)(nil), "controller.GetReleaseRequest")
	proto.RegisterType((*StreamAppLogRequest)(nil), "controller.StreamAppLogRequest")
	proto.RegisterType((*CreateReleaseRequest)(nil), "controller.CreateReleaseRequest")
	proto.RegisterType((*CreateDeploymentRequest)(nil), "controller.CreateDeploymentRequest")
	proto.RegisterType((*StreamEventsRequest)(nil), "controller.StreamEventsRequest")
	proto.RegisterType((*App)(nil), "controller.App")
	proto.RegisterMapType((map[string]string)(nil), "controller.App.LabelsEntry")
	proto.RegisterType((*Release)(nil), "controller.Release")
	proto.RegisterMapType((map[string]string)(nil), "controller.Release.EnvEntry")
	proto.RegisterMapType((map[string]string)(nil), "controller.Release.LabelsEntry")
	proto.RegisterMapType((map[string]*ProcessType)(nil), "controller.Release.ProcessesEntry")
	proto.RegisterType((*Deployment)(nil), "controller.Deployment")
	proto.RegisterMapType((map[string]int32)(nil), "controller.Deployment.ProcessesEntry")
	proto.RegisterMapType((map[string]*DeploymentProcessTags)(nil), "controller.Deployment.TagsEntry")
	proto.RegisterType((*DeploymentProcessTags)(nil), "controller.DeploymentProcessTags")
	proto.RegisterMapType((map[string]string)(nil), "controller.DeploymentProcessTags.TagsEntry")
	proto.RegisterType((*Event)(nil), "controller.Event")
	proto.RegisterType((*ProcessType)(nil), "controller.ProcessType")
	proto.RegisterMapType((map[string]string)(nil), "controller.ProcessType.EnvEntry")
	proto.RegisterMapType((map[string]*HostResourceSpec)(nil), "controller.ProcessType.ResourcesEntry")
	proto.RegisterType((*Port)(nil), "controller.Port")
	proto.RegisterType((*VolumeReq)(nil), "controller.VolumeReq")
	proto.RegisterType((*HostService)(nil), "controller.HostService")
	proto.RegisterType((*HostHealthCheck)(nil), "controller.HostHealthCheck")
	proto.RegisterType((*HostResourceSpec)(nil), "controller.HostResourceSpec")
	proto.RegisterType((*HostMount)(nil), "controller.HostMount")
	proto.RegisterType((*LibContainerDevice)(nil), "controller.LibContainerDevice")
	proto.RegisterType((*LogChunk)(nil), "controller.LogChunk")
	proto.RegisterType((*LogAggregatorLogOpts)(nil), "controller.LogAggregatorLogOpts")
	proto.RegisterEnum("controller.LogAggregatorStreamType", LogAggregatorStreamType_name, LogAggregatorStreamType_value)
	proto.RegisterEnum("controller.LogAggregatorStreamSource", LogAggregatorStreamSource_name, LogAggregatorStreamSource_value)
	proto.RegisterEnum("controller.Deployment_Status", Deployment_Status_name, Deployment_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*App, error)
	GetRelease(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*Release, error)
	StreamAppLog(ctx context.Context, in *StreamAppLogRequest, opts ...grpc.CallOption) (Controller_StreamAppLogClient, error)
	CreateRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*Release, error)
	CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (Controller_StreamEventsClient, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, "/controller.Controller/ListApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := c.cc.Invoke(ctx, "/controller.Controller/GetApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetRelease(ctx context.Context, in *GetReleaseRequest, opts ...grpc.CallOption) (*Release, error) {
	out := new(Release)
	err := c.cc.Invoke(ctx, "/controller.Controller/GetRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) StreamAppLog(ctx context.Context, in *StreamAppLogRequest, opts ...grpc.CallOption) (Controller_StreamAppLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Controller_serviceDesc.Streams[0], "/controller.Controller/StreamAppLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerStreamAppLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_StreamAppLogClient interface {
	Recv() (*LogChunk, error)
	grpc.ClientStream
}

type controllerStreamAppLogClient struct {
	grpc.ClientStream
}

func (x *controllerStreamAppLogClient) Recv() (*LogChunk, error) {
	m := new(LogChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) CreateRelease(ctx context.Context, in *CreateReleaseRequest, opts ...grpc.CallOption) (*Release, error) {
	out := new(Release)
	err := c.cc.Invoke(ctx, "/controller.Controller/CreateRelease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*Deployment, error) {
	out := new(Deployment)
	err := c.cc.Invoke(ctx, "/controller.Controller/CreateDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (Controller_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Controller_serviceDesc.Streams[1], "/controller.Controller/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_StreamEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type controllerStreamEventsClient struct {
	grpc.ClientStream
}

func (x *controllerStreamEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	GetApp(context.Context, *GetAppRequest) (*App, error)
	GetRelease(context.Context, *GetReleaseRequest) (*Release, error)
	StreamAppLog(*StreamAppLogRequest, Controller_StreamAppLogServer) error
	CreateRelease(context.Context, *CreateReleaseRequest) (*Release, error)
	CreateDeployment(context.Context, *CreateDeploymentRequest) (*Deployment, error)
	StreamEvents(*StreamEventsRequest, Controller_StreamEventsServer) error
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.Controller/ListApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.Controller/GetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.Controller/GetRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetRelease(ctx, req.(*GetReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_StreamAppLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAppLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).StreamAppLog(m, &controllerStreamAppLogServer{stream})
}

type Controller_StreamAppLogServer interface {
	Send(*LogChunk) error
	grpc.ServerStream
}

type controllerStreamAppLogServer struct {
	grpc.ServerStream
}

func (x *controllerStreamAppLogServer) Send(m *LogChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_CreateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.Controller/CreateRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateRelease(ctx, req.(*CreateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.Controller/CreateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateDeployment(ctx, req.(*CreateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).StreamEvents(m, &controllerStreamEventsServer{stream})
}

type Controller_StreamEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type controllerStreamEventsServer struct {
	grpc.ServerStream
}

func (x *controllerStreamEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApps",
			Handler:    _Controller_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _Controller_GetApp_Handler,
		},
		{
			MethodName: "GetRelease",
			Handler:    _Controller_GetRelease_Handler,
		},
		{
			MethodName: "CreateRelease",
			Handler:    _Controller_CreateRelease_Handler,
		},
		{
			MethodName: "CreateDeployment",
			Handler:    _Controller_CreateDeployment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAppLog",
			Handler:       _Controller_StreamAppLog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _Controller_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 2169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x18, 0xdb, 0x72, 0x1c, 0x47,
	0xd5, 0xab, 0xbd, 0x68, 0xf6, 0x8c, 0x24, 0xaf, 0xdb, 0x8a, 0xbd, 0x5e, 0x5f, 0x24, 0x8f, 0x63,
	0x47, 0x95, 0x20, 0x29, 0x51, 0x12, 0x0c, 0x24, 0x01, 0x14, 0x49, 0xb1, 0x55, 0xc8, 0x2b, 0x55,
	0x4b, 0x06, 0xca, 0x2f, 0x5b, 0xa3, 0x9d, 0xf6, 0x68, 0xac, 0xd9, 0xe9, 0xc9, 0x74, 0xaf, 0x64,
	0x25, 0xf8, 0x05, 0xbe, 0x80, 0xe2, 0x81, 0x2a, 0xaa, 0xe0, 0x0f, 0xf8, 0x02, 0x9e, 0xf8, 0x06,
	0x7e, 0x00, 0xaa, 0x78, 0xe5, 0x03, 0x78, 0xa3, 0xfa, 0x74, 0xcf, 0xec, 0xcc, 0xee, 0xc8, 0xb2,
	0xf1, 0x5b, 0x9f, 0x5b, 0x77, 0x9f, 0x5b, 0x9f, 0xd3, 0x07, 0x5a, 0x7d, 0x1e, 0xc9, 0x84, 0x87,
	0x21, 0x4b, 0x56, 0xe2, 0x84, 0x4b, 0x4e, 0x60, 0x84, 0xe9, 0xdc, 0xf2, 0x39, 0xf7, 0x43, 0xb6,
	0xea, 0xc6, 0xc1, 0xaa, 0x1b, 0x45, 0x5c, 0xba, 0x32, 0xe0, 0x91, 0xd0, 0x9c, 0x9d, 0x05, 0x43,
	0x45, 0xe8, 0x70, 0xf8, 0x7c, 0x55, 0x06, 0x03, 0x26, 0xa4, 0x3b, 0x88, 0x0d, 0xc3, 0x9d, 0x71,
	0x06, 0x6f, 0x98, 0xe0, 0x0e, 0x86, 0x7e, 0x63, 0x9c, 0xee, 0x46, 0x67, 0x9a, 0xe4, 0x3c, 0x81,
	0xcb, 0x3b, 0x81, 0x90, 0xeb, 0x71, 0x2c, 0x28, 0xfb, 0x76, 0xc8, 0x84, 0x24, 0x37, 0xa1, 0x19,
	0xbb, 0x3e, 0xeb, 0x89, 0xe0, 0x3b, 0xd6, 0xae, 0x2c, 0x56, 0x96, 0xea, 0xd4, 0x52, 0x88, 0xfd,
	0xe0, 0x3b, 0x46, 0x6e, 0x03, 0x20, 0x51, 0xf2, 0x63, 0x16, 0xb5, 0xa7, 0x16, 0x2b, 0x4b, 0x4d,
	0x8a, 0xec, 0x07, 0x0a, 0xe1, 0xf4, 0xa0, 0x35, 0xda, 0x4e, 0xc4, 0x3c, 0x12, 0x8c, 0xdc, 0x83,
	0x9a, 0x1b, 0xc7, 0xa2, 0x5d, 0x59, 0xac, 0x2e, 0xd9, 0x6b, 0x97, 0x57, 0x72, 0x96, 0x58, 0x8f,
	0x63, 0x8a, 0x44, 0xf2, 0x00, 0x2e, 0x47, 0xec, 0xa5, 0xec, 0x4d, 0x6c, 0x3e, 0xab, 0xd0, 0x7b,
	0xd9, 0x01, 0xf7, 0x60, 0xf6, 0x11, 0x53, 0xfb, 0xa7, 0xb7, 0x25, 0x50, 0x8b, 0xdc, 0x81, 0xbe,
	0x68, 0x93, 0xe2, 0xda, 0xf9, 0x00, 0xae, 0x3c, 0x62, 0x92, 0xb2, 0x90, 0xb9, 0x82, 0xbd, 0x8e,
	0xb1, 0x07, 0x57, 0xf7, 0x65, 0xc2, 0xdc, 0xc1, 0x7a, 0x1c, 0xef, 0x70, 0xff, 0x35, 0xac, 0xe4,
	0x33, 0xa8, 0xf1, 0x58, 0x0a, 0xbc, 0x95, 0xbd, 0xb6, 0x98, 0xd7, 0x62, 0x87, 0xfb, 0xeb, 0xbe,
	0x9f, 0x30, 0xdf, 0x95, 0x3c, 0xd9, 0xe1, 0xfe, 0x6e, 0x2c, 0x05, 0x45, 0x6e, 0xe7, 0x37, 0x30,
	0xbf, 0x91, 0x30, 0x57, 0xb2, 0xb1, 0xcb, 0x5c, 0x83, 0x46, 0xec, 0x26, 0x2c, 0x92, 0xe6, 0x0c,
	0x03, 0x91, 0x65, 0x98, 0x4e, 0x34, 0xa7, 0x39, 0xe8, 0x6a, 0xfe, 0xa0, 0x74, 0x93, 0x94, 0x47,
	0x79, 0x23, 0xd1, 0x3b, 0xf6, 0x02, 0xaf, 0x5d, 0xd5, 0xde, 0x30, 0x98, 0x6d, 0xcf, 0x79, 0x01,
	0xd7, 0xf5, 0xe9, 0x9b, 0x2c, 0x0e, 0xf9, 0xd9, 0x80, 0x45, 0xf2, 0xa2, 0x0b, 0xb4, 0x8b, 0x17,
	0x68, 0xbe, 0xf1, 0x59, 0x7f, 0xac, 0xa4, 0xb6, 0xdc, 0x3a, 0x61, 0x91, 0x14, 0x17, 0x1d, 0x74,
	0x17, 0x66, 0xf8, 0xe1, 0x0b, 0xd6, 0x97, 0x3d, 0x79, 0x16, 0x33, 0x65, 0xd7, 0xea, 0x52, 0x93,
	0xda, 0x1a, 0x77, 0xa0, 0x50, 0x2a, 0x10, 0x0d, 0x4b, 0x76, 0xa0, 0xa5, 0x11, 0xdb, 0x9e, 0xf2,
	0x51, 0xcc, 0x85, 0x6c, 0xd7, 0x16, 0x2b, 0x4b, 0x16, 0xc5, 0x35, 0x99, 0x87, 0x7a, 0x9f, 0x0f,
	0x23, 0xd9, 0xae, 0x63, 0xd4, 0x6a, 0xc0, 0xf9, 0x5d, 0x15, 0xaa, 0xeb, 0x71, 0x5c, 0xea, 0xd5,
	0xbb, 0x30, 0xe3, 0x05, 0x22, 0x0e, 0xdd, 0xb3, 0x1e, 0xd2, 0xb4, 0xce, 0xb6, 0xc1, 0x75, 0x15,
	0xcb, 0xa7, 0xd0, 0x08, 0xdd, 0x43, 0x16, 0x8a, 0x76, 0x15, 0x03, 0xf8, 0xe6, 0x58, 0x00, 0xaf,
	0xec, 0x20, 0x75, 0x2b, 0x92, 0xc9, 0x19, 0x35, 0xac, 0xe4, 0x0b, 0xb0, 0xfb, 0x68, 0xf9, 0x9e,
	0xca, 0x55, 0xbc, 0xa4, 0xbd, 0xd6, 0x59, 0xd1, 0x79, 0xb8, 0x92, 0xe6, 0xe1, 0xca, 0x41, 0x9a,
	0xc8, 0x14, 0x34, 0xbb, 0x42, 0x28, 0xe1, 0x61, 0xec, 0x65, 0xc2, 0xf5, 0x8b, 0x85, 0x35, 0x3b,
	0x0a, 0xdf, 0x87, 0x39, 0x0f, 0xbd, 0x8d, 0xc2, 0x7c, 0x28, 0xdb, 0x0d, 0x34, 0xc6, 0xac, 0xc6,
	0x1e, 0x68, 0x24, 0xe9, 0x80, 0x25, 0x64, 0xe2, 0x4a, 0xe6, 0x9f, 0xb5, 0xa7, 0xb5, 0x69, 0x53,
	0x38, 0x1f, 0x03, 0x56, 0x21, 0x06, 0x3a, 0x3f, 0x06, 0x3b, 0xa7, 0x2d, 0x69, 0x41, 0xf5, 0x98,
	0x9d, 0x19, 0x83, 0xaa, 0xa5, 0xf2, 0xc0, 0x89, 0x1b, 0x0e, 0x53, 0x43, 0x6a, 0xe0, 0x27, 0x53,
	0x3f, 0xaa, 0x38, 0xff, 0xa9, 0xc2, 0xb4, 0x89, 0xdf, 0x52, 0x4f, 0xdc, 0x82, 0xa6, 0x9b, 0xc8,
	0xe0, 0xb9, 0xdb, 0x97, 0xda, 0xd2, 0x4d, 0x3a, 0x42, 0x90, 0x15, 0xa8, 0xb2, 0xe8, 0xa4, 0x5d,
	0x43, 0x0f, 0xdc, 0x2a, 0xc9, 0x89, 0x95, 0xad, 0xe8, 0x44, 0xbb, 0x40, 0x31, 0x92, 0x87, 0x99,
	0xd3, 0xea, 0x28, 0xb2, 0x50, 0x26, 0x52, 0xe6, 0xb8, 0x9f, 0x43, 0x33, 0x4e, 0x78, 0x9f, 0x09,
	0xc1, 0x44, 0xbb, 0x81, 0xb2, 0x4e, 0x99, 0xec, 0x5e, 0xca, 0xa4, 0xc5, 0x47, 0x42, 0xe3, 0xae,
	0x9f, 0x7e, 0x1b, 0xd7, 0x77, 0x7e, 0x08, 0x56, 0xaa, 0xc8, 0xdb, 0x58, 0xf7, 0x1d, 0x1c, 0xd3,
	0x79, 0x0a, 0x73, 0x45, 0x65, 0x4a, 0xa4, 0x97, 0xf3, 0xd2, 0xf6, 0xda, 0xf5, 0xbc, 0x45, 0x8c,
	0xb0, 0x4a, 0xd9, 0xbc, 0xbf, 0xff, 0x59, 0x07, 0x18, 0x3d, 0x3b, 0xa5, 0x2e, 0x5f, 0x00, 0x9b,
	0x87, 0x5e, 0x2f, 0x8d, 0x35, 0x9d, 0xe1, 0xc0, 0x43, 0x2f, 0x8d, 0x93, 0x05, 0xb0, 0x23, 0x76,
	0x9a, 0x31, 0xd4, 0x34, 0x43, 0xc4, 0x4e, 0x53, 0x86, 0x7c, 0x14, 0xd7, 0xc7, 0xa2, 0xf8, 0x73,
	0x68, 0x08, 0xe9, 0xca, 0xa1, 0xc0, 0x04, 0x98, 0x5b, 0xbb, 0x9d, 0xbf, 0xf4, 0xe8, 0x66, 0x2b,
	0xfb, 0xc8, 0x44, 0x0d, 0x33, 0xd9, 0xc8, 0x07, 0xc0, 0x34, 0x06, 0xc0, 0xfd, 0x73, 0x24, 0xcf,
	0x8f, 0x81, 0xcf, 0xa0, 0x26, 0x5d, 0x5f, 0xb4, 0x2d, 0x94, 0x5f, 0x3c, 0x47, 0xfe, 0xc0, 0xf5,
	0x8d, 0x28, 0x72, 0x97, 0xa4, 0x6e, 0xb3, 0x2c, 0x75, 0xc7, 0x02, 0x0c, 0xde, 0xf6, 0x6d, 0x61,
	0x2f, 0xe3, 0x20, 0x31, 0xc2, 0xf6, 0xc5, 0xc2, 0x9a, 0x1d, 0x85, 0x3f, 0x07, 0x8b, 0x45, 0x9e,
	0x96, 0x9c, 0xb9, 0x50, 0x72, 0x9a, 0x45, 0x1e, 0x06, 0xf5, 0x97, 0x6f, 0x10, 0x61, 0x85, 0xf8,
	0xac, 0xe7, 0xe3, 0xf3, 0x19, 0x34, 0x33, 0x43, 0x95, 0x08, 0x3e, 0x2c, 0x86, 0xe6, 0xdd, 0x72,
	0x5b, 0xa7, 0x41, 0xea, 0xfa, 0x22, 0x1f, 0xa4, 0x5f, 0x42, 0x43, 0xbb, 0x9f, 0xd8, 0x30, 0xbd,
	0xb7, 0xd5, 0xdd, 0xdc, 0xee, 0x3e, 0x6a, 0x5d, 0x22, 0x00, 0x8d, 0x6f, 0xd6, 0xb7, 0x77, 0xb6,
	0x36, 0x5b, 0x15, 0x45, 0xa0, 0x4f, 0xbb, 0x5d, 0x45, 0x98, 0x22, 0x33, 0x60, 0x6d, 0xec, 0x3e,
	0xd9, 0xdb, 0xd9, 0x3a, 0xd8, 0x6a, 0x55, 0x9d, 0xdf, 0x57, 0xe0, 0xbd, 0xd2, 0x23, 0xc8, 0xcf,
	0x8c, 0xff, 0x75, 0xcb, 0xf3, 0xd1, 0x85, 0x77, 0x1a, 0x0f, 0x85, 0xce, 0xc3, 0xd7, 0x2b, 0x7d,
	0xfe, 0x33, 0xfb, 0xa7, 0x0a, 0xd4, 0xb1, 0x00, 0x97, 0x66, 0xdc, 0xa8, 0x18, 0x4f, 0x15, 0x8a,
	0xf1, 0x12, 0xd4, 0x3c, 0x57, 0xba, 0x98, 0x82, 0xf6, 0xda, 0xfc, 0x84, 0x53, 0xd7, 0xa3, 0x33,
	0x8a, 0x1c, 0xef, 0x54, 0xd8, 0x9c, 0xff, 0xd6, 0xc1, 0xce, 0x3d, 0x17, 0xea, 0x8a, 0x6e, 0x62,
	0xcc, 0xd4, 0xa4, 0xb8, 0x26, 0x6b, 0xfa, 0xa5, 0x9f, 0x9a, 0xcc, 0x9c, 0x9c, 0xe4, 0xd8, 0x6b,
	0xff, 0x00, 0xea, 0x31, 0x4f, 0x64, 0x5a, 0xa1, 0x5b, 0x05, 0x29, 0x9e, 0x48, 0xaa, 0xc9, 0x64,
	0x15, 0xa6, 0x4f, 0x78, 0x38, 0x1c, 0x30, 0x61, 0x2a, 0xc9, 0x7b, 0x79, 0xce, 0x5f, 0x22, 0x89,
	0xb2, 0x6f, 0x69, 0xca, 0xa5, 0x2e, 0xc8, 0x07, 0x51, 0x80, 0x6f, 0x8b, 0x45, 0x71, 0xad, 0x5a,
	0x86, 0x23, 0x2e, 0x64, 0x2f, 0x62, 0xf2, 0x94, 0x27, 0xc7, 0xf8, 0xba, 0x58, 0xd4, 0x56, 0xb8,
	0xae, 0x46, 0x91, 0x1f, 0x00, 0x41, 0x96, 0x38, 0xf0, 0xb0, 0xad, 0x10, 0xb1, 0xdb, 0xd7, 0x95,
	0xc0, 0xa2, 0x2d, 0x45, 0xd9, 0x0b, 0xbc, 0x6e, 0x8a, 0x57, 0xe5, 0x56, 0xb0, 0xe4, 0x24, 0xe8,
	0x67, 0xe5, 0xd6, 0x80, 0xaa, 0x26, 0x26, 0x4c, 0x0c, 0x93, 0x84, 0xf5, 0xf5, 0x5b, 0x60, 0xd1,
	0x11, 0x82, 0x6c, 0x22, 0x95, 0x0f, 0x93, 0x3e, 0x13, 0x6d, 0x40, 0x7d, 0x1e, 0x9c, 0x67, 0x2f,
	0x9a, 0x32, 0x9a, 0xa7, 0x2a, 0x13, 0x24, 0xcb, 0xd0, 0x18, 0xa8, 0x36, 0x49, 0xb4, 0xed, 0x49,
	0x93, 0x3c, 0xe6, 0x42, 0x3e, 0x51, 0x54, 0x6a, 0x98, 0xc8, 0x32, 0x90, 0x30, 0x88, 0x86, 0x2f,
	0x7b, 0x7d, 0x37, 0x76, 0x0f, 0x83, 0x30, 0x90, 0x01, 0x13, 0xed, 0x19, 0x74, 0xe0, 0x15, 0xa4,
	0x6c, 0xe4, 0x08, 0xe4, 0x11, 0x5c, 0x76, 0xc3, 0x90, 0x9f, 0x32, 0xaf, 0xe7, 0x31, 0xa5, 0x93,
	0x68, 0xcf, 0xe2, 0x31, 0x77, 0x0a, 0x0d, 0x74, 0x70, 0xb8, 0xc1, 0x23, 0xe9, 0x06, 0x11, 0x4b,
	0x36, 0x91, 0x8d, 0xce, 0x19, 0x31, 0x0d, 0x0a, 0xf2, 0x11, 0x5c, 0x39, 0x4d, 0x02, 0xc9, 0xdc,
	0xc3, 0x90, 0xf5, 0xfa, 0x7e, 0xc2, 0x87, 0xb1, 0x68, 0xcf, 0x69, 0x8b, 0x66, 0x84, 0x0d, 0x8d,
	0xff, 0xbf, 0xab, 0xe8, 0x33, 0x98, 0x2b, 0x1a, 0xaa, 0x44, 0x7a, 0xad, 0xf8, 0xde, 0xdc, 0x1a,
	0x37, 0x57, 0xba, 0xc1, 0x7e, 0xcc, 0xfa, 0xf9, 0xc4, 0xec, 0x43, 0x4d, 0x85, 0xa2, 0xee, 0x5b,
	0x13, 0x69, 0x3e, 0x56, 0xb8, 0x56, 0x37, 0xc2, 0xcc, 0x49, 0x6f, 0xa4, 0x3f, 0x88, 0x9f, 0x8c,
	0xe2, 0xa2, 0x3a, 0x59, 0x76, 0xd5, 0x59, 0xfb, 0x9a, 0x9c, 0x05, 0x8c, 0xb3, 0x05, 0xcd, 0x2c,
	0x8a, 0xf1, 0x24, 0x57, 0x1e, 0xa5, 0x0f, 0x80, 0x5a, 0x93, 0xf7, 0x55, 0x89, 0x09, 0x99, 0x64,
	0x3d, 0x1e, 0xf5, 0x84, 0xe4, 0x31, 0x1e, 0x69, 0xd1, 0x19, 0x8d, 0xdd, 0x8d, 0xf6, 0x25, 0x8f,
	0x9d, 0xef, 0xc1, 0xce, 0x6d, 0x3f, 0xd1, 0x24, 0x57, 0x26, 0x9b, 0xe4, 0x6b, 0xd0, 0xd0, 0x79,
	0x6e, 0xf6, 0x33, 0x10, 0xf9, 0x04, 0xea, 0xfd, 0x23, 0xd6, 0x3f, 0x36, 0x1a, 0xdc, 0x1c, 0xd7,
	0xe0, 0x31, 0x73, 0x43, 0x79, 0xb4, 0xa1, 0x58, 0xa8, 0xe6, 0x74, 0xfe, 0x3a, 0x05, 0x97, 0xc7,
	0x48, 0x4a, 0x15, 0xf5, 0x4b, 0x48, 0x55, 0x51, 0x6b, 0x55, 0x8c, 0x82, 0x48, 0xb2, 0xe4, 0xc4,
	0x0d, 0xcd, 0xee, 0x37, 0x26, 0x9e, 0xa1, 0x4d, 0xf3, 0x0f, 0xa6, 0x19, 0xab, 0xca, 0x29, 0x79,
	0x94, 0x30, 0x71, 0xc4, 0x43, 0x0f, 0x9f, 0xaf, 0x3a, 0x1d, 0x21, 0xd4, 0x97, 0xe3, 0x38, 0x08,
	0xc3, 0x9e, 0xc7, 0x4f, 0x23, 0x93, 0xf5, 0x96, 0x42, 0x6c, 0xf2, 0xd3, 0x88, 0xfc, 0x14, 0x66,
	0x85, 0x74, 0x13, 0x59, 0xe8, 0xac, 0x5f, 0x7b, 0xec, 0x0c, 0xf2, 0xa7, 0x85, 0x3b, 0x75, 0xc8,
	0x74, 0xce, 0x21, 0x04, 0x6a, 0xea, 0x41, 0x30, 0x99, 0x8f, 0x6b, 0x15, 0x0e, 0x03, 0x57, 0xf6,
	0x8f, 0x30, 0xe5, 0x9b, 0x54, 0x03, 0xca, 0xc4, 0xa6, 0x9f, 0x01, 0xbc, 0xb5, 0x81, 0x9c, 0xaf,
	0xa1, 0x35, 0x1e, 0x77, 0xba, 0x83, 0xc7, 0xff, 0x17, 0x9a, 0xac, 0x4a, 0x53, 0x50, 0xed, 0x1d,
	0x06, 0x83, 0x40, 0x17, 0x80, 0x2a, 0xd5, 0x80, 0xf3, 0xe7, 0x0a, 0x34, 0xb3, 0x5c, 0x57, 0x5d,
	0x55, 0xc8, 0xfb, 0xa8, 0x81, 0xb1, 0x78, 0x06, 0xab, 0x5b, 0x48, 0x37, 0xf1, 0x59, 0x56, 0x41,
	0x34, 0xa4, 0x64, 0x54, 0x1a, 0xaa, 0x2c, 0x44, 0x6f, 0x58, 0x34, 0x83, 0x95, 0x8c, 0x4e, 0x7e,
	0xd3, 0xc1, 0x19, 0x48, 0xe9, 0x8e, 0x55, 0x47, 0x77, 0x6e, 0xba, 0xbe, 0xcc, 0x43, 0xfd, 0x79,
	0xa8, 0x4a, 0xa7, 0xfe, 0xb5, 0x68, 0xc0, 0xf9, 0x57, 0x05, 0xc8, 0xe4, 0x23, 0x51, 0x08, 0x8b,
	0xba, 0x09, 0x8b, 0xd4, 0xc8, 0x53, 0x39, 0x23, 0xa3, 0x41, 0x5f, 0xf0, 0x04, 0x6f, 0x56, 0xa5,
	0x1a, 0x40, 0x6c, 0x10, 0xf1, 0x04, 0x6f, 0xa5, 0xb0, 0x0a, 0x20, 0x8b, 0x60, 0xc7, 0x2c, 0x19,
	0x04, 0x42, 0x04, 0x3c, 0x12, 0xe6, 0x6e, 0x79, 0x94, 0x8a, 0x91, 0xe7, 0x41, 0xc8, 0x7a, 0x03,
	0xee, 0x31, 0xbc, 0xe6, 0x2c, 0xb5, 0x14, 0xe2, 0x09, 0xf7, 0x98, 0x7a, 0x30, 0x86, 0x81, 0x87,
	0x2e, 0x9e, 0xa5, 0x6a, 0xa9, 0x30, 0x7e, 0xe0, 0xa1, 0x83, 0x67, 0xa9, 0x5a, 0xaa, 0x83, 0xf1,
	0x75, 0x33, 0x4f, 0xba, 0x06, 0x9c, 0xbf, 0x4c, 0x81, 0xb5, 0xc3, 0xfd, 0x8d, 0xa3, 0x61, 0x74,
	0x9c, 0x85, 0x45, 0x25, 0x17, 0x16, 0x2d, 0xa8, 0xbe, 0xe0, 0x87, 0x46, 0x31, 0xb5, 0x54, 0x98,
	0x81, 0xf0, 0x4d, 0xe3, 0xac, 0x96, 0x2a, 0x55, 0x4d, 0x17, 0x8a, 0xdf, 0x6a, 0x63, 0x70, 0x3b,
	0xce, 0x15, 0xdd, 0xaf, 0xa0, 0xa1, 0x23, 0x05, 0x75, 0x9b, 0x2b, 0x76, 0xb7, 0x85, 0x51, 0x86,
	0xfe, 0xce, 0xef, 0x23, 0x33, 0x35, 0x42, 0xe4, 0x0b, 0x15, 0x86, 0x0a, 0x6f, 0xda, 0xea, 0x7b,
	0x17, 0x88, 0xe3, 0xbf, 0xc0, 0x88, 0xbc, 0xd3, 0xdf, 0xc8, 0xf9, 0x7b, 0x05, 0xe6, 0xcb, 0x46,
	0x2d, 0x2a, 0xbe, 0x9e, 0x73, 0x34, 0x68, 0x45, 0x3f, 0x3e, 0x1a, 0x2a, 0x31, 0x18, 0x46, 0x7f,
	0xc4, 0x04, 0x9a, 0xac, 0x4e, 0x35, 0xf0, 0x26, 0x46, 0xfb, 0x06, 0x66, 0xb4, 0x0a, 0x66, 0x5a,
	0xa1, 0x7e, 0x95, 0x6f, 0xa8, 0xbb, 0x2d, 0xb2, 0xb5, 0xf8, 0xf0, 0x31, 0x5c, 0x3f, 0x87, 0x4f,
	0x35, 0x9d, 0xfb, 0x07, 0x9b, 0xbb, 0x4f, 0x0f, 0x74, 0x03, 0xba, 0x7f, 0xb0, 0xb9, 0x45, 0x69,
	0xab, 0x42, 0x2c, 0xa8, 0x6d, 0x77, 0xb7, 0x0f, 0x5a, 0x53, 0xaa, 0x15, 0x7d, 0xda, 0xfd, 0x45,
	0x77, 0xf7, 0x57, 0xdd, 0x56, 0xf5, 0xc3, 0xf7, 0xe1, 0xc6, 0xb9, 0xce, 0x22, 0xd3, 0x50, 0x5d,
	0xdf, 0xdb, 0x6b, 0x5d, 0x5a, 0xfb, 0x5b, 0x1d, 0x60, 0x23, 0xbb, 0x23, 0x79, 0x04, 0x56, 0x3a,
	0x9e, 0x23, 0x37, 0x8b, 0x15, 0xb8, 0x30, 0x03, 0xec, 0xdc, 0x2a, 0x27, 0xea, 0x89, 0x9e, 0x73,
	0x89, 0xec, 0x42, 0x43, 0x8f, 0xe1, 0xc8, 0x8d, 0x3c, 0x67, 0x61, 0x34, 0xd7, 0x19, 0x1f, 0xf5,
	0x39, 0x37, 0x7e, 0xfb, 0x8f, 0x7f, 0xff, 0x61, 0xea, 0x2a, 0xb9, 0xb2, 0x7a, 0xb2, 0xb6, 0xfa,
	0xbd, 0xaa, 0x25, 0x5f, 0xb9, 0x71, 0x2c, 0x56, 0x97, 0x5f, 0x11, 0x1f, 0x60, 0x34, 0xb2, 0x23,
	0xb7, 0xc7, 0x36, 0x2d, 0x4e, 0xcf, 0x3a, 0x65, 0x43, 0x31, 0xe7, 0x3e, 0x6e, 0xbe, 0x40, 0x6e,
	0xe3, 0xe6, 0x85, 0xdd, 0x57, 0xcd, 0x0f, 0x52, 0xac, 0x2e, 0x13, 0x1f, 0x66, 0xf2, 0x23, 0x3f,
	0x52, 0x98, 0x0c, 0x94, 0x0c, 0x03, 0x3b, 0xf3, 0x63, 0x4e, 0xc6, 0x04, 0x75, 0xee, 0xe0, 0x69,
	0x6d, 0x72, 0x6d, 0x42, 0x95, 0xd5, 0x90, 0xfb, 0xaf, 0x3e, 0xae, 0x90, 0x01, 0xcc, 0x16, 0x46,
	0x7f, 0xa4, 0xd0, 0xcc, 0x96, 0x4d, 0x05, 0x5f, 0xab, 0x97, 0xa3, 0xf5, 0xd2, 0x0d, 0xfb, 0x84,
	0x62, 0xaf, 0xc8, 0x4b, 0x68, 0x8d, 0xcf, 0xfa, 0xc8, 0xbd, 0xc9, 0x13, 0x27, 0x26, 0x81, 0x9d,
	0x6b, 0xe5, 0xbf, 0x13, 0xe7, 0x03, 0x3c, 0xf7, 0xae, 0xb3, 0x50, 0x76, 0xae, 0x97, 0xf1, 0x09,
	0xf2, 0xeb, 0xd4, 0xa2, 0x7a, 0xf0, 0x57, 0x66, 0xd1, 0xc2, 0x48, 0xb0, 0x73, 0x25, 0xcf, 0x80,
	0x24, 0x87, 0xe0, 0x61, 0x33, 0x04, 0xd4, 0x61, 0x0c, 0xb9, 0x3f, 0xae, 0x7c, 0xdd, 0x7a, 0x36,
	0x37, 0xe2, 0xf4, 0x93, 0xb8, 0x7f, 0xd8, 0xc0, 0x37, 0xe2, 0xd3, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xe8, 0x54, 0x2f, 0xb9, 0x4f, 0x17, 0x00, 0x00,
}
